# Generated by Django 4.0.5 on 2022-06-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ipoteka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='', max_length=100)),
                ('term_min', models.IntegerField(default=0)),
                ('term_max', models.IntegerField(default=0)),
                ('rate_min', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('rate_max', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('payment_min', models.BigIntegerField(default=0)),
                ('payment_max', models.BigIntegerField(default=0)),
            ],
        ),
    ]
