# Generated by Django 4.0.5 on 2022-06-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipoteka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipoteka',
            name='rate_max',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='ipoteka',
            name='rate_min',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
