# Generated by Django 4.0.5 on 2022-06-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipoteka', '0002_alter_ipoteka_rate_max_alter_ipoteka_rate_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipoteka',
            name='rate_max',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ipoteka',
            name='rate_min',
            field=models.FloatField(default=0),
        ),
    ]
