# Generated by Django 4.0.5 on 2022-07-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipoteka', '0003_alter_ipoteka_rate_max_alter_ipoteka_rate_min'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipoteka',
            options={'ordering': ['id']},
        ),
    ]
